### ISSUE TITLE
How do I pass properties such as split, binary?

### ISSUE THREAD

**Issue by hibaahsan** [vaibhavad/python-wrapper-OpenIE5#2]
I have tried passing a dictionary such as properties = {'binary':True, 'split': True} when invoking extractor.extract but it is not making a difference.

**Comment by vaibhavad** [comment]
Hi,

These arguments should be mentioned when starting the OpenIE5 server. For example - 
java -Xmx10-XX:+UseConcMarkSweepGC -jar openie-assembly-5.0-SNAPSHOT.jar --binary --ignore-errors --httpPort 8000

Also, --split is an argument applicable when there is an input file, not when using OpenIE5 as a server. However, you should be able to see binary(triples) output if you start the server with --binary argument and get extraction via this python wrapper.

For more details on command line arguments please see -https://github.com/dair-iitd/OpenIE-standalone#command-line-interface
