### ISSUE TITLE
Server does not seem to be able to take incoming requests from multiple IPs

### ISSUE THREAD

**Issue by Weilin37** [vaibhavad/python-wrapper-OpenIE5#5]
I am hosting the server on an EC2 instance. I then make a request from another computer and it seems to work fine. However, when a second computer tries to make a request, the code hangs and the request doesn't seem to be able to make it to the server. Weirdly enough, the original computer will start having the same problem too.

**Comment by vaibhavad** [comment]
Hi @Weilin37,

Do you see anything unusual in the logs on EC2, where OpenIE5 is hosted?

**Comment by Weilin37** [comment]
Hi,

I think i know what the problem is. My second computer was using https rather than http

**Comment by vaibhavad** [comment]
Good to know you worked it out. Closing this issue.
